### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by sonesmj** [honza-kasik/check-for-files#4]
sonesmj@download6:~/checksftp/check-for-files$ ./check_for_files.py
Traceback (most recent call last):
  File "./check_for_files.py", line 11, in <module>
    from tinydb.middlewares import SerializationMiddleware
ImportError: cannot import name 'SerializationMiddleware'

I believe I have the required modules:-
sonesmj@download6:~/checksftp/check-for-files$ sudo -H pip3.6 install tinydb_serialization
Requirement already satisfied: tinydb_serialization in /usr/local/lib/python3.6/dist-packages (1.0.4)
Requirement already satisfied: tinydb>=2.2.1 in /usr/local/lib/python3.6/dist-packages (from tinydb_serialization) (3.11.1)

**Comment by honza-kasik** [comment]
Hi @sonesmj ! Thanks for your report, can you please check if #5 fixes the issue for you?

**Comment by sonesmj** [comment]
Do you know what, I just made the same edits myself, locally !   :-)

**Comment by honza-kasik** [comment]
@sonesmj That's great! So it works? I no longer use it, so if it works for you I'll merge it.

**Comment by sonesmj** [comment]
Yup, cheers

**Comment by honza-kasik** [comment]
@sonesmj Thank you very much again! :+1:
